# env/platform-agnostic-pns hasn't been publically released, so you will install it from master
PIPELINE_VERSION = "2.0.5"
k8s_yaml(
    kustomize(
        "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources" +
        "?ref={v}".format(v=PIPELINE_VERSION)
    )
)

# kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
k8s_yaml(
    kustomize(
        "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns" +
        "?ref={v}".format(v=PIPELINE_VERSION)
    )
)
